spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example_db
    username: example_user
    password: 1234
    pool:
      enabled: true
      max-size: 10
      max-idle-time: 10m
      initial-size: 1
  webflux:
    problemdetails:
      enabled: true
springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,openapi,swagger-ui,live,liveness,readiness
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
debug: true
