#react:
#  db:
#    url: "jdbc:postgresql://localhost:5432/example_db"
#    username: example_user
#    password: 1234
#    driver: org.postgresql.Driver

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example_db
    username: example_user
    password: 1234
    pool:
      enabled: true
      max-size: 10
      max-idle-time: 10m
      initial-size: 1
